version: '3'
  
services:
  db-login-service:
    image: postgres
    environment:
      - POSTGRES_DB=login_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=group22
    ports:
      - ${POSTGRES_LOGIN_PORT}:5432

  db-traveler-service:
    image: postgres
    environment:
      - POSTGRES_DB=traveler_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=group22
    ports:
      - ${POSTGRES_TRAVELER_PORT}:5432

  db-ticket-catalog-service:
    image: postgres
    environment:
      - POSTGRES_DB=ticket_catalog_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=group22
    ports:
      - ${POSTGRES_TICKET_CATALOG_PORT}:5432